server:
  port: 10011
spring:
  application:
    name: leyou-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  #        git:
#          uri: https://github.com/lyj8330328/leyou-config.git
  rabbitmq:
    host: 127.0.0.1
    username: /leyou
    password: leyou
    virtual-host: /leyou


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
